services:
  # A Docker web service
  - type: web
    name: vjianban
    env: docker
    repo: https://github.com # optional
    region: Singapore  # optional (defaults to oregon)
    plan: free # optional (defaults to starter)
    healthCheckPath: /
    envVars:
      - key: ID
        value: ad806487-2d26-4636-98b6-ab85cc852111
      - key: WSPATH
        value: /
      
